#port chec
---
- name: To check telnet port
  hosts: all
  tasks:
  - name: test connectivity
    shell:
      cmd: nc -vz {{ inventory_hostname }} {{ port_number }}
    register: result

  - name: Show result
    debug:
      var: result
