- name: Test Telnet Connectivity
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Test Telnet Connection
      wait_for:
        host: "{{ destination_ip }}"
        port: 22
        state: started
      register: telnet_result
  
    - name: Print Telnet Result
      debug:
        var: telnet_result
