- name: Get the list of all the nodes which are running over a month
  hosts: all
  gather_facts: false
  tasks:

      - name: Show hostname for sanity check (or just use -v flag for verbose)
        command: hostname
        register: hostname
      - debug: var=hostname.stdout_lines

      - name: Check uptime prior reboot
        shell: cut -d ' ' -f1 /proc/uptime
        register: UPTIME_PRE_REBOOT
      - debug: var=UPTIME_PRE_REBOOT
   
