---
- name: Display system uptime
  hosts: your_server_group
  gather_facts: yes

  tasks:
    - name: Get uptime
      command: uptime -s
      register: uptime_output

    - name: Calculate number of days
      set_fact:
        uptime_days: "{{ (ansible_date_time.epoch | float - uptime_output.stdout | float) / 86400 | int }}"

    - name: Display system uptime
      debug:
        msg: "System uptime: {{ uptime_days }} days"
