---
- name: Display hostname and uptime
  hosts: all
  gather_facts: yes

  tasks:
    - name: Get hostname
      command: hostname
      register: hostname_output

    - name: Get uptime
      command: uptime |cut -d " " -f 4
      register: uptime_output

    - name: Display hostname and uptime
      debug:
        msg: "Hostname: {{ hostname_output.stdout }} - Uptime: {{ uptime_output.stdout }} days"
